<?php

namespace AppBundle\Repository;

/**
 * CartePredictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartePredictionRepository extends \Doctrine\ORM\EntityRepository
{
}
